# Generated by Django 4.2.1 on 2023-09-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
